### BASIC SETTINGS ###

# Name of analyst
analyst_name: "RWS"

# Which modules to run (false or true)
module_stats: true
module_assessment: true
module_trend: true
module_baseline: true
module_power: true

# Period to analyse (YYYY-mm-dd)
min_date: 2012-01-01
max_date: 2017-12-31

# Percentage of total abundance to analyse (0 < percentage_total_abundance <= 100)
percentage_total_abundance: 80

# Litter type to analyse 
# (e.g., OSPAR codes in square brackets
# and [TA] for total abundance)
litter_type: [[TA], [49]]

# Threshold value analysis

# Assessment type: mean or median
assessment_statistic: median

# Threshold group or type
threshold_type: [TA]

# Threshold value: natural number
threshold_value: 15

# Image quality: high or low
image_quality: high

### ADVANCED SETTINGS ###

# Power-analysis: number of Monte Carlo simulations
# Note that larger values lead to longer run times.
# The default number of simulations is 100 to speed up computation. 
# However, 1000 simulations generally give more accurate results
number_of_simulations: 100

# Power-analysis: significance level
alpha: 0.05

# Power-analysis: resolution of effect size (range: 5% ... 50%)
resolution_effect_size: 10

# Power-analysis: minimum number of surveys to sample from
min_surveys: 16

# Show source code? (true or false)
show_source_code: false