# litteR settings file

# Period to analyse (YYYY-mm-dd)
date_min: 2012-01-01
date_max: 2017-12-31

# Percentage of total count to analyse (0 < percentage_total_count <= 100)
percentage_total_count: 80

# Data file. Note: the datafile must be in the same path as the settings file
file_data: beach-litter-nl-2012-2017.csv

# Type file. Defines the types and their groups
file_types: types-ospar.csv

# Select trend figures to plot in the report
spatial_code: ["Noordwijk", "Terschelling"]
group_code: ["TC", "SUP", "FISH"]
type_name: ["Plastic: Bags [2]"]
figure_quality: low
